# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20161217_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cover', models.FileField(upload_to=b'')),
                ('desc', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Cause')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Ngo')),
            ],
        ),
    ]
